// error

// const x = 2;

// x = 5;

// console.log("Hello");
// error handling
// try {

// } catch (error) {

// }

// try {
//   const x = 0;
//   x = 5;
// } catch (error) {
//   console.log(error.message);
// } finally {
//   console.log("Namaste");
// }
